import { AnimatedText, PKeyframe } from "./types";
import * as fabric from "fabric";
import { FabricObject } from "fabric";
import { LygenObject } from "./types";

/**
 * All the possible properties of an object
 * @type {string[]}
 */
export const props = [
  "left",
  "top",
  "scaleX",
  "scaleY",
  "width",
  "height",
  "angle",
  "opacity",
  "fill",
  "strokeWidth",
  "stroke",
  "shadow.color",
  "shadow.opacity",
  "shadow.offsetX",
  "shadow.offsetY",
  "shadow.blur",
  "charSpacing",
  "lineHeight",
];
/**
 * p_keyframes is an array of default keyframes (generated by the system).
 * @note [start, end] is the range on which you can trim the object.
 * [trimstart, trimend] is the range on which the object actually animates.
 * @type {Array<{
 *   start: number, // The start time from where you CANNOT trim the object anymore ahead
 *   end: number,   // The end time where you CANNOT trim the object anymore behind
 *   trimstart: number,  // The start time OFFSET from [start] where you can trim the object
 *   trimend: number,   // The end time OFFSET from [end] where you can trim the object
 *   object: Object,
 *   id: string
 * }>}
 */
export const p_keyframes: PKeyframe[] = [];
export const allObjects: LygenObject[] = [];
export const allAnimatedTexts: FabricObject[] = [];
export const activeLyrics: Map<number, AnimatedText[]> = new Map();
